# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Windows x64 Build

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      sign_windows:
        description: 'Sign the Windows installer (requires a valid, non-expired code-signing certificate in the CERT_WINDOWS secret)'
        type: boolean
        default: false

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [24]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Retrieve the settings and write them to a file
      shell: pwsh    
      env:
        SETTINGS_FILE: ${{ secrets.SETTINGS_FILE }}
      run: |
        $env:SETTINGS_FILE | Out-File .\config\settings.json
        dir .\config

    - name: Generate certificate file from secret
      if: ${{ inputs.sign_windows == true }}
      shell: pwsh
      env:
        SETTINGS_FILE: ${{ secrets.CERT_WINDOWS }}
      run: |
        New-Item -ItemType Directory -Force -Path .\certs
        $encodedBytes = [System.Convert]::FromBase64String("${{ secrets.CERT_WINDOWS }}");      
        Set-Content .\certs\installer.pfx -Value $encodedBytes -AsByteStream;
        dir .\certs

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v7
      with:
        node-version: ${{ matrix.node-version }}

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3

    - name: Build Installer
      env:
        RELEASE_SERVER: ${{ secrets.RELEASE_SERVER }}
        SIGN_WINDOWS: ${{ inputs.sign_windows }}
      run: |
        $env:BUILD_TARGET = "dist"
        npm install
        npm run make
  
    - uses: actions/upload-artifact@v7
      with:
        name: package
        path: ./out/make/squirrel.windows/x64/

  